version: '3.8'

services:
  spark-master:
    build: .
    image: custom-spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    networks:
      - animeverse-net

  spark-worker:
    build: .
    image: custom-spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8080"
    volumes:
      - ./data:/data
    networks:
      - animeverse-net

networks:
  animeverse-net:
    external: true
